"""Enrichment tier 0: a built-in name -> (icon_slug, category) map.

Applied synchronously at add time, before/without any LLM call, so common
UK-household groceries get a real line icon and aisle offline, free, instantly.

Icons are monochrome line icons from the Tabler vocabulary
(https://tabler.io/icons); values are Tabler slugs, verified against
``@tabler/icons`` 3.x. Many-to-one is deliberate — a small, coherent vocabulary
(all cheeses -> ``cheese``, every fizzy drink -> ``bottle``) reads better than
per-item uniqueness. ``ICON_VOCABULARY`` is the sorted unique slug list, shared
by the client build and the LLM enrich prompt.

Keys are ``name_norm`` values (lowercase, whitespace-collapsed) kept singular
so the plural-stripping fallback in :func:`lookup` reaches them. Category values
are exact ``DEFAULT_WALK_ORDER`` strings.
"""

from __future__ import annotations

FRUIT_VEG = "Fruit & Veg"
BAKERY = "Bakery"
MEAT_FISH = "Meat & Fish"
DAIRY = "Dairy & Eggs"
CUPBOARD = "Cupboard"
FROZEN = "Frozen"
DRINKS = "Drinks"
HOUSEHOLD = "Household"
PET = "Pet"
OTHER = "Other"

BUILTIN: dict[str, tuple[str, str]] = {
    # --- Fruit & Veg --------------------------------------------------
    "apple": ("apple", FRUIT_VEG),
    "banana": ("banana", FRUIT_VEG),
    "orange": ("lemon", FRUIT_VEG),
    "satsuma": ("lemon", FRUIT_VEG),
    "clementine": ("lemon", FRUIT_VEG),
    "grapefruit": ("lemon", FRUIT_VEG),
    "lemon": ("lemon", FRUIT_VEG),
    "lime": ("lemon", FRUIT_VEG),
    "grape": ("grape", FRUIT_VEG),
    "raisin": ("grape", FRUIT_VEG),
    "strawberry": ("cherry", FRUIT_VEG),
    "raspberry": ("cherry", FRUIT_VEG),
    "blueberry": ("cherry", FRUIT_VEG),
    "blackberry": ("cherry", FRUIT_VEG),
    "cherry": ("cherry", FRUIT_VEG),
    "plum": ("cherry", FRUIT_VEG),
    "fig": ("cherry", FRUIT_VEG),
    "melon": ("apple", FRUIT_VEG),
    "watermelon": ("apple", FRUIT_VEG),
    "pineapple": ("apple", FRUIT_VEG),
    "mango": ("apple", FRUIT_VEG),
    "peach": ("apple", FRUIT_VEG),
    "nectarine": ("apple", FRUIT_VEG),
    "pear": ("apple", FRUIT_VEG),
    "kiwi": ("apple", FRUIT_VEG),
    "coconut": ("apple", FRUIT_VEG),
    "date": ("apple", FRUIT_VEG),
    "avocado": ("avocado", FRUIT_VEG),
    "tomato": ("apple", FRUIT_VEG),
    "carrot": ("carrot", FRUIT_VEG),
    "parsnip": ("carrot", FRUIT_VEG),
    "potato": ("plant", FRUIT_VEG),
    "sweet potato": ("plant", FRUIT_VEG),
    "turnip": ("plant", FRUIT_VEG),
    "swede": ("plant", FRUIT_VEG),
    "beetroot": ("plant", FRUIT_VEG),
    "radish": ("plant", FRUIT_VEG),
    "onion": ("plant", FRUIT_VEG),
    "spring onion": ("plant", FRUIT_VEG),
    "shallot": ("plant", FRUIT_VEG),
    "garlic": ("plant", FRUIT_VEG),
    "leek": ("plant", FRUIT_VEG),
    "ginger": ("plant", FRUIT_VEG),
    "peas": ("plant", FRUIT_VEG),
    "green bean": ("plant", FRUIT_VEG),
    "sweetcorn": ("plant", FRUIT_VEG),
    "corn": ("plant", FRUIT_VEG),
    "butternut squash": ("plant", FRUIT_VEG),
    "pumpkin": ("plant", FRUIT_VEG),
    "broccoli": ("salad", FRUIT_VEG),
    "cauliflower": ("salad", FRUIT_VEG),
    "cabbage": ("salad", FRUIT_VEG),
    "lettuce": ("salad", FRUIT_VEG),
    "spinach": ("salad", FRUIT_VEG),
    "kale": ("salad", FRUIT_VEG),
    "celery": ("salad", FRUIT_VEG),
    "asparagus": ("salad", FRUIT_VEG),
    "brussels sprout": ("salad", FRUIT_VEG),
    "rhubarb": ("salad", FRUIT_VEG),
    "salad": ("salad", FRUIT_VEG),
    "cucumber": ("salad", FRUIT_VEG),
    "courgette": ("salad", FRUIT_VEG),
    "aubergine": ("salad", FRUIT_VEG),
    "pepper": ("pepper", FRUIT_VEG),
    "chilli": ("pepper", FRUIT_VEG),
    "mushroom": ("mushroom", FRUIT_VEG),
    "herb": ("leaf", FRUIT_VEG),
    "basil": ("leaf", FRUIT_VEG),
    "coriander": ("leaf", FRUIT_VEG),
    "parsley": ("leaf", FRUIT_VEG),
    "mint": ("leaf", FRUIT_VEG),

    # --- Bakery -------------------------------------------------------
    "bread": ("bread", BAKERY),
    "white bread": ("bread", BAKERY),
    "brown bread": ("bread", BAKERY),
    "wholemeal bread": ("bread", BAKERY),
    "sourdough": ("bread", BAKERY),
    "brioche": ("bread", BAKERY),
    "teacake": ("bread", BAKERY),
    "hot cross bun": ("bread", BAKERY),
    "baguette": ("baguette", BAKERY),
    "french stick": ("baguette", BAKERY),
    "roll": ("bread", BAKERY),
    "bread roll": ("bread", BAKERY),
    "bap": ("bread", BAKERY),
    "bun": ("bread", BAKERY),
    "bagel": ("bread", BAKERY),
    "croissant": ("bread", BAKERY),
    "pain au chocolat": ("bread", BAKERY),
    "pastry": ("bread", BAKERY),
    "pitta": ("bread", BAKERY),
    "pita": ("bread", BAKERY),
    "wrap": ("bread", BAKERY),
    "tortilla": ("bread", BAKERY),
    "naan": ("bread", BAKERY),
    "flatbread": ("bread", BAKERY),
    "crumpet": ("bread", BAKERY),
    "pancake": ("cake", BAKERY),
    "muffin": ("cake", BAKERY),
    "cupcake": ("cake", BAKERY),
    "cake": ("cake", BAKERY),
    "scone": ("cake", BAKERY),
    "pie": ("cake", BAKERY),
    "doughnut": ("cookie", BAKERY),
    "donut": ("cookie", BAKERY),
    "cookie": ("cookie", BAKERY),
    "biscuit": ("cookie", BAKERY),

    # --- Meat & Fish --------------------------------------------------
    "chicken": ("meat", MEAT_FISH),
    "chicken breast": ("meat", MEAT_FISH),
    "chicken thigh": ("meat", MEAT_FISH),
    "turkey": ("meat", MEAT_FISH),
    "duck": ("meat", MEAT_FISH),
    "beef": ("meat", MEAT_FISH),
    "steak": ("meat", MEAT_FISH),
    "mince": ("meat", MEAT_FISH),
    "beef mince": ("meat", MEAT_FISH),
    "lamb": ("meat", MEAT_FISH),
    "pork": ("meat", MEAT_FISH),
    "gammon": ("meat", MEAT_FISH),
    "bacon": ("meat", MEAT_FISH),
    "ham": ("meat", MEAT_FISH),
    "burger": ("meat", MEAT_FISH),
    "meatball": ("meat", MEAT_FISH),
    "ribs": ("meat", MEAT_FISH),
    "chop": ("meat", MEAT_FISH),
    "sausage": ("sausage", MEAT_FISH),
    "fish": ("fish", MEAT_FISH),
    "salmon": ("fish", MEAT_FISH),
    "tuna": ("fish", MEAT_FISH),
    "cod": ("fish", MEAT_FISH),
    "haddock": ("fish", MEAT_FISH),
    "mackerel": ("fish", MEAT_FISH),
    "sardine": ("fish", MEAT_FISH),
    "trout": ("fish", MEAT_FISH),
    "sea bass": ("fish", MEAT_FISH),
    "fish finger": ("fish", MEAT_FISH),
    "prawn": ("fish", MEAT_FISH),
    "shrimp": ("fish", MEAT_FISH),
    "crab": ("fish", MEAT_FISH),
    "lobster": ("fish", MEAT_FISH),
    "mussel": ("fish", MEAT_FISH),
    "scallop": ("fish", MEAT_FISH),
    "squid": ("fish", MEAT_FISH),
    "calamari": ("fish", MEAT_FISH),

    # --- Dairy & Eggs -------------------------------------------------
    "milk": ("milk", DAIRY),
    "semi skimmed milk": ("milk", DAIRY),
    "skimmed milk": ("milk", DAIRY),
    "whole milk": ("milk", DAIRY),
    "oat milk": ("milk", DAIRY),
    "almond milk": ("milk", DAIRY),
    "soya milk": ("milk", DAIRY),
    "cream": ("milk", DAIRY),
    "double cream": ("milk", DAIRY),
    "single cream": ("milk", DAIRY),
    "soured cream": ("milk", DAIRY),
    "creme fraiche": ("milk", DAIRY),
    "custard": ("milk", DAIRY),
    "yoghurt": ("milk", DAIRY),
    "yogurt": ("milk", DAIRY),
    "butter": ("milk", DAIRY),
    "margarine": ("milk", DAIRY),
    "spread": ("milk", DAIRY),
    "cheese": ("cheese", DAIRY),
    "cheddar": ("cheese", DAIRY),
    "mozzarella": ("cheese", DAIRY),
    "parmesan": ("cheese", DAIRY),
    "brie": ("cheese", DAIRY),
    "feta": ("cheese", DAIRY),
    "halloumi": ("cheese", DAIRY),
    "cream cheese": ("cheese", DAIRY),
    "egg": ("egg", DAIRY),

    # --- Cupboard -----------------------------------------------------
    "pasta": ("bowl", CUPBOARD),
    "spaghetti": ("bowl", CUPBOARD),
    "penne": ("bowl", CUPBOARD),
    "fusilli": ("bowl", CUPBOARD),
    "lasagne": ("bowl", CUPBOARD),
    "macaroni": ("bowl", CUPBOARD),
    "noodle": ("bowl", CUPBOARD),
    "rice": ("bowl", CUPBOARD),
    "basmati rice": ("bowl", CUPBOARD),
    "risotto rice": ("bowl", CUPBOARD),
    "couscous": ("bowl", CUPBOARD),
    "quinoa": ("bowl", CUPBOARD),
    "cereal": ("bowl", CUPBOARD),
    "porridge": ("bowl", CUPBOARD),
    "oats": ("bowl", CUPBOARD),
    "cornflakes": ("bowl", CUPBOARD),
    "muesli": ("bowl", CUPBOARD),
    "granola": ("bowl", CUPBOARD),
    "soup": ("soup", CUPBOARD),
    "beans": ("soup", CUPBOARD),
    "baked beans": ("soup", CUPBOARD),
    "kidney bean": ("soup", CUPBOARD),
    "chickpea": ("soup", CUPBOARD),
    "lentil": ("soup", CUPBOARD),
    "tin": ("soup", CUPBOARD),
    "tinned tomato": ("soup", CUPBOARD),
    "chopped tomato": ("soup", CUPBOARD),
    "tomato puree": ("soup", CUPBOARD),
    "passata": ("soup", CUPBOARD),
    "gravy": ("soup", CUPBOARD),
    # Coconut milk/cream come in a tin — the canned-goods icon in Cupboard, not
    # the "coconut" -> "apple" fruit fallback (Tabler has no coconut glyph).
    "coconut milk": ("soup", CUPBOARD),
    "coconut cream": ("soup", CUPBOARD),
    "flour": ("wheat", CUPBOARD),
    "yeast": ("wheat", CUPBOARD),
    "sugar": ("salt", CUPBOARD),
    "salt": ("salt", CUPBOARD),
    "spice": ("salt", CUPBOARD),
    "pepper spice": ("salt", CUPBOARD),
    "paprika": ("salt", CUPBOARD),
    "cinnamon": ("salt", CUPBOARD),
    "curry powder": ("salt", CUPBOARD),
    "stock cube": ("salt", CUPBOARD),
    "baking powder": ("salt", CUPBOARD),
    "oil": ("bottle", CUPBOARD),
    "olive oil": ("bottle", CUPBOARD),
    "vegetable oil": ("bottle", CUPBOARD),
    "sunflower oil": ("bottle", CUPBOARD),
    "vinegar": ("bottle", CUPBOARD),
    "ketchup": ("bottle", CUPBOARD),
    "mayonnaise": ("bottle", CUPBOARD),
    "mustard": ("bottle", CUPBOARD),
    "brown sauce": ("bottle", CUPBOARD),
    "soy sauce": ("bottle", CUPBOARD),
    "pasta sauce": ("bottle", CUPBOARD),
    "curry sauce": ("bottle", CUPBOARD),
    "stir fry sauce": ("bottle", CUPBOARD),
    "salad dressing": ("bottle", CUPBOARD),
    "jam": ("candy", CUPBOARD),
    "marmalade": ("candy", CUPBOARD),
    "honey": ("candy", CUPBOARD),
    "sweets": ("candy", CUPBOARD),
    "sweet": ("candy", CUPBOARD),
    "chewing gum": ("candy", CUPBOARD),
    "crisp": ("candy", CUPBOARD),
    "crisps": ("candy", CUPBOARD),
    "popcorn": ("candy", CUPBOARD),
    "chocolate": ("chocolate", CUPBOARD),
    "chocolate bar": ("chocolate", CUPBOARD),
    "chocolate spread": ("chocolate", CUPBOARD),
    "nutella": ("chocolate", CUPBOARD),
    "hot chocolate": ("chocolate", CUPBOARD),
    "nuts": ("acorn", CUPBOARD),
    "peanut": ("acorn", CUPBOARD),
    "almond": ("acorn", CUPBOARD),
    "peanut butter": ("acorn", CUPBOARD),
    "cracker": ("cookie", CUPBOARD),
    "olive": ("salad", CUPBOARD),
    "gherkin": ("salad", CUPBOARD),
    "pickle": ("salad", CUPBOARD),
    "tea": ("cup", CUPBOARD),
    "tea bag": ("cup", CUPBOARD),
    "coffee": ("coffee", CUPBOARD),

    # --- Frozen -------------------------------------------------------
    "ice cream": ("ice-cream", FROZEN),
    "ice lolly": ("ice-cream", FROZEN),
    "frozen peas": ("snowflake", FROZEN),
    "frozen chips": ("snowflake", FROZEN),
    "oven chips": ("snowflake", FROZEN),
    "chips": ("snowflake", FROZEN),
    "waffle": ("snowflake", FROZEN),
    "ice": ("snowflake", FROZEN),
    "pizza": ("pizza", FROZEN),
    "frozen pizza": ("pizza", FROZEN),

    # --- Drinks -------------------------------------------------------
    "water": ("droplet", DRINKS),
    "sparkling water": ("droplet", DRINKS),
    "juice": ("bottle", DRINKS),
    "orange juice": ("bottle", DRINKS),
    "apple juice": ("bottle", DRINKS),
    "squash": ("bottle", DRINKS),
    "cordial": ("bottle", DRINKS),
    "lemonade": ("bottle", DRINKS),
    "cola": ("bottle", DRINKS),
    "coke": ("bottle", DRINKS),
    "fizzy drink": ("bottle", DRINKS),
    "soft drink": ("bottle", DRINKS),
    "smoothie": ("bottle", DRINKS),
    "energy drink": ("bottle", DRINKS),
    "beer": ("beer", DRINKS),
    "lager": ("beer", DRINKS),
    "ale": ("beer", DRINKS),
    "cider": ("beer", DRINKS),
    "wine": ("glass-full", DRINKS),
    "red wine": ("glass-full", DRINKS),
    "white wine": ("glass-full", DRINKS),
    "rose wine": ("glass-full", DRINKS),
    "prosecco": ("glass-champagne", DRINKS),
    "champagne": ("glass-champagne", DRINKS),
    "gin": ("glass-cocktail", DRINKS),
    "vodka": ("glass-cocktail", DRINKS),
    "whisky": ("glass-cocktail", DRINKS),
    "whiskey": ("glass-cocktail", DRINKS),
    "rum": ("glass-cocktail", DRINKS),
    "brandy": ("glass-cocktail", DRINKS),

    # --- Household ----------------------------------------------------
    "toilet roll": ("toilet-paper", HOUSEHOLD),
    "loo roll": ("toilet-paper", HOUSEHOLD),
    "toilet paper": ("toilet-paper", HOUSEHOLD),
    "kitchen roll": ("toilet-paper", HOUSEHOLD),
    "tissue": ("toilet-paper", HOUSEHOLD),
    "kleenex": ("toilet-paper", HOUSEHOLD),
    "wipe": ("toilet-paper", HOUSEHOLD),
    "baby wipe": ("toilet-paper", HOUSEHOLD),
    "sanitary towel": ("toilet-paper", HOUSEHOLD),
    "tampon": ("toilet-paper", HOUSEHOLD),
    "cotton bud": ("toilet-paper", HOUSEHOLD),
    "cotton wool": ("package", HOUSEHOLD),
    "bin bag": ("trash", HOUSEHOLD),
    "bin liner": ("trash", HOUSEHOLD),
    "washing up liquid": ("spray", HOUSEHOLD),
    "fairy liquid": ("spray", HOUSEHOLD),
    "dishwasher tablet": ("spray", HOUSEHOLD),
    "bleach": ("spray", HOUSEHOLD),
    "disinfectant": ("spray", HOUSEHOLD),
    "surface spray": ("spray", HOUSEHOLD),
    "cleaner": ("spray", HOUSEHOLD),
    "cleaning spray": ("spray", HOUSEHOLD),
    "air freshener": ("spray", HOUSEHOLD),
    "washing powder": ("wash-machine", HOUSEHOLD),
    "laundry detergent": ("wash-machine", HOUSEHOLD),
    "fabric softener": ("wash-machine", HOUSEHOLD),
    "soap": ("bottle", HOUSEHOLD),
    "hand soap": ("bottle", HOUSEHOLD),
    "shampoo": ("bottle", HOUSEHOLD),
    "conditioner": ("bottle", HOUSEHOLD),
    "shower gel": ("bottle", HOUSEHOLD),
    "body wash": ("bottle", HOUSEHOLD),
    "mouthwash": ("bottle", HOUSEHOLD),
    "deodorant": ("bottle", HOUSEHOLD),
    "shaving foam": ("bottle", HOUSEHOLD),
    "sun cream": ("bottle", HOUSEHOLD),
    "moisturiser": ("bottle", HOUSEHOLD),
    "sponge": ("brush", HOUSEHOLD),
    "scourer": ("brush", HOUSEHOLD),
    "cloth": ("brush", HOUSEHOLD),
    "toothpaste": ("dental", HOUSEHOLD),
    "toothbrush": ("dental", HOUSEHOLD),
    "razor": ("razor", HOUSEHOLD),
    "paracetamol": ("pills", HOUSEHOLD),
    "ibuprofen": ("pills", HOUSEHOLD),
    "vitamin": ("pills", HOUSEHOLD),
    "plaster": ("first-aid-kit", HOUSEHOLD),
    "battery": ("battery", HOUSEHOLD),
    "light bulb": ("bulb", HOUSEHOLD),
    "matches": ("flame", HOUSEHOLD),
    "candle": ("candle", HOUSEHOLD),
    "foil": ("package", HOUSEHOLD),
    "cling film": ("package", HOUSEHOLD),
    "baking paper": ("package", HOUSEHOLD),
    "freezer bag": ("package", HOUSEHOLD),
    "sandwich bag": ("package", HOUSEHOLD),
    "nappy": ("diaper", HOUSEHOLD),

    # --- Pet ----------------------------------------------------------
    "dog food": ("dog", PET),
    "dog": ("dog", PET),
    "dog treat": ("bone", PET),
    "cat food": ("cat", PET),
    "cat treat": ("cat", PET),
    "cat litter": ("cat", PET),
    "cat": ("cat", PET),
    "pet food": ("paw", PET),
    "rabbit food": ("paw", PET),
    "hamster food": ("paw", PET),
    "fish food": ("fish", PET),
    "bird seed": ("feather", PET),
}

ICON_VOCABULARY: list[str] = sorted({slug for slug, _category in BUILTIN.values()})


def lookup(name_norm: str) -> tuple[str, str] | None:
    """Return ``(icon_slug, category)`` for ``name_norm`` or ``None``.

    Tries, in order: an exact key match; a trailing-``s`` singular match
    (``eggs`` -> ``egg``); then the longest built-in key that is contained
    in ``name_norm`` (``cherry tomatoes`` -> ``tomato``), requiring a key of
    at least four characters to avoid spurious substring hits.
    """
    if name_norm in BUILTIN:
        return BUILTIN[name_norm]
    if name_norm.endswith("s") and name_norm[:-1] in BUILTIN:
        return BUILTIN[name_norm[:-1]]
    best: str | None = None
    best_rank: tuple[int, int] = (0, -1)
    for key in BUILTIN:
        if len(key) < 4:
            continue
        pos = name_norm.find(key)
        if pos == -1:
            continue
        # Prefer the longest key; on a tie prefer the later match, which in
        # English is usually the head noun ("cherry tomatoes" -> tomato).
        rank = (len(key), pos)
        if best is None or rank > best_rank:
            best, best_rank = key, rank
    return BUILTIN[best] if best is not None else None
