// Generates src/theme.css from the Catppuccin palette.
// Run: node scripts/gen-theme.mjs > src/theme.css
// Emits, per flavour, a [data-flavour="..."] block covering all 26 colors,
// plus a :root default of Mocha and a light-scheme default of Latte (only
// when no explicit data-flavour is set). Accent is indirected through
// --accent, overridable via data-accent.
import { flavors } from '@catppuccin/palette';

const FLAVOURS = ['mocha', 'latte', 'frappe', 'macchiato'];

function vars(flavour, indent) {
  const pad = ' '.repeat(indent);
  return Object.entries(flavors[flavour].colors)
    .map(([name, c]) => `${pad}--ctp-${name}: ${c.hex};`)
    .join('\n');
}

function accentBlock(indent) {
  const pad = ' '.repeat(indent);
  return `${pad}--accent: var(--ctp-peach);`;
}

let out = `/* GENERATED by scripts/gen-theme.mjs — do not edit by hand. */\n`;

// Explicit flavour selection.
for (const f of FLAVOURS) {
  out += `\n[data-flavour="${f}"] {\n${vars(f, 2)}\n}\n`;
}

// Defaults when no explicit data-flavour attribute is set: Mocha (dark),
// overridden by Latte under a light colour-scheme preference.
out += `\n:root:not([data-flavour]) {\n${vars('mocha', 2)}\n}\n`;
out += `\n@media (prefers-color-scheme: light) {\n  :root:not([data-flavour]) {\n${vars('latte', 4)}\n  }\n}\n`;

// Accent indirection: default to peach, overridable via data-accent="<color>".
out += `\n:root {\n${accentBlock(2)}\n}\n`;
for (const [name] of Object.entries(flavors.mocha.colors)) {
  out += `[data-accent="${name}"] { --accent: var(--ctp-${name}); }\n`;
}

process.stdout.write(out);
