// Emits src/lib/icons.ts: an inline-SVG map for exactly the Tabler outline
// icons the app uses, so the bundle stays tree-shaken and works offline.
// Run: node scripts/gen-icons.mjs > src/lib/icons.ts
//
// Two kinds of entries:
//  - the server's icon-slug vocabulary (enrichment tier 0), parsed straight
//    out of server/trug/icons.py so the client map can never drift from what
//    the server emits in `item.icon`;
//  - UI_SLUGS: chrome icons (basket, shelf labels, …) referenced directly by
//    components (CATEGORY_ICON in walkOrder.ts and inline usages).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(here, '../node_modules/@tabler/icons/icons/outline');

/** Server vocabulary: every distinct slug in BUILTIN's (slug, category) pairs. */
const serverMap = readFileSync(join(here, '../../server/trug/icons.py'), 'utf8');
const ITEM_SLUGS = [...new Set([...serverMap.matchAll(/\(\s*"([a-z0-9-]+)"\s*,\s*[A-Z_]+\s*\)/g)].map((m) => m[1]))];
if (ITEM_SLUGS.length < 40) throw new Error(`suspiciously few server slugs parsed (${ITEM_SLUGS.length})`);

/** Chrome icons used directly by components. */
const UI_SLUGS = [
  'basket',
  'settings',
  'x',
  'pencil',
  'plus',
  // Header copy-list button: rest state + brief "copied" confirmation swap.
  'copy',
  'copy-check',
  // Connections section: reveal/hide toggle for masked tokens.
  'eye',
  'eye-off',
  // Settings disclosures: rotating chevron on each collapsible section header.
  'chevron-right',
  // Aisle shelf-label icons (CATEGORY_ICON) not already in the vocabulary.
  'archive',
  'glass-full',
  'leaf-2',
  // Medicines shelf label: the single tablet, against the `pills` pair on its rows.
  'pill',
  // Right-swipe reveal: the gesture checks the item off, so it shows a tick.
  'check',
  'shopping-bag',
  'clock',
  // Add bar: the voice-input button, on devices whose browser can hear.
  'microphone',
];

function inner(name) {
  const svg = readFileSync(join(iconsDir, `${name}.svg`), 'utf8');
  const body = svg.replace(/^[\s\S]*?>/, '').replace(/<\/svg>\s*$/, '');
  return body
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.includes('stroke="none"')) // drop the 24x24 no-op background path
    .join('');
}

const all = [...new Set([...ITEM_SLUGS, ...UI_SLUGS])].sort();
const entries = all
  .map((slug) => `  '${slug}': '${inner(slug).replace(/'/g, "\\'")}',`)
  .join('\n');

process.stdout.write(`// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Tabler outline icons (MIT), inlined as 24x24 stroke paths for offline use.
// Render inside: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor"
// stroke-width="2" stroke-linecap="round" stroke-linejoin="round">.
export const ICONS: Record<string, string> = {
${entries}
};

/** True when the map has an inline icon for this slug. */
export function hasIcon(slug: string): boolean {
  return Object.prototype.hasOwnProperty.call(ICONS, slug);
}
`);
